name: HeneriaBedwars
main: fr.heneria.bedwars.HeneriaBedwarsPlugin
version: "${version}"
api-version: "1.21"
authors: [ "Heneria" ]
description: "HeneriaBedwars (Spigot 1.21) - étape 1"
website: "https://github.com/tomashb/HeneriaBedwars"
commands:
  hbw:
    description: Commande HeneriaBedwars
    usage: "/hbw <version|reload|help>"
    permission: "heneria.use"
permissions:
  heneria.use:
    default: true
  heneria.admin:
    default: op
