name: HeneriaBedwars
main: gg.heneria.bedwars.HeneriaBedwarsPlugin
version: 0.0.1
api-version: '1.21'
author: Heneria
description: BedWars plugin for Spigot 1.21 (bootstrap stage)
website: https://github.com/tomashb/HeneriaBedwars
permissions:
  heneria.admin:
    description: Accès aux commandes d'administration HeneriaBedwars
    default: op
