name: 💡 Feature request
description: Proposer une amélioration
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Problème / opportunité
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposition
  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      options: [low, medium, high]
      default: 1
