name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle (no wrapper)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Ensure no Gradle wrapper committed
        run: |
          test ! -e gradlew && test ! -e gradlew.bat && test ! -d gradle || \
          (echo "Gradle wrapper détecté, interdit à l'étape 1"; exit 1)

      - name: Build & Unit Tests
        run: gradle build --stacktrace --warning-mode all

      - name: Quality (Checkstyle + Coverage)
        run: |
          gradle check jacocoTestReport --stacktrace
          echo "Checkstyle: build/reports/checkstyle/"
          echo "JaCoCo HTML: build/reports/jacoco/test/html/index.html"

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: HeneriaBedwars-${{ github.sha }}
          path: build/libs/*.jar

      - name: Upload QA reports
        uses: actions/upload-artifact@v4
        with:
          name: qa-reports-${{ github.sha }}
          path: |
            build/reports/checkstyle/**
            build/reports/jacoco/test/**
