name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'  # active le cache deps Gradle

      - name: Setup Gradle (no wrapper)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Ensure no Gradle wrapper committed
        run: |
          test ! -e gradlew && test ! -e gradlew.bat && test ! -d gradle || \
          (echo "Gradle wrapper détecté, interdit à l'étape 1"; exit 1)

      - name: Build
        run: gradle build --stacktrace --warning-mode all

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: HeneriaBedwars-${{ github.sha }}
          path: build/libs/*.jar
