name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle (no wrapper)
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle version
        run: gradle --version

      - name: Compile & Test (no jar)
        run: gradle compileJava test --no-daemon

      - name: Assert no JAR produced
        run: |
          if ls build/libs/*.jar 2>/dev/null; then
            echo "JAR found but should not be produced on CI."
            exit 1
          else
            echo "OK: no JAR produced."
          fi
