name: Release Drafter
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronized]
permissions:
  contents: write
  pull-requests: write
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
